FROM ann-benchmarks

RUN apt-get update
RUN apt-get install -y git cmake g++ python3 python3-setuptools python3-pip
RUN pip3 install wheel pybind11
RUN git clone https://gitee.com/zivChen/qbg-test.git
RUN mkdir -p qbg-test/build
RUN cd qbg-test/build && cmake ..
RUN cd qbg-test/build && make && make install
RUN ldconfig
RUN cd qbg-test/python && python3 setup.py bdist_wheel
RUN pip3 install qbg-test/python/dist/ngt-*-linux_x86_64.whl